import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../core/providers.dart';
import '../../core/utils/formatters.dart';
import '../../domain/models.dart';
import '../../shared/widgets.dart';
import '../accounts/accounts_page.dart';

class DashboardPage extends ConsumerWidget {
  const DashboardPage({super.key});
  @override Widget build(BuildContext context, WidgetRef ref) {
    final totals=ref.watch(dashboardProvider),currency=ref.watch(baseCurrencyProvider),transactions=ref.watch(transactionsProvider(null)),accounts=ref.watch(accountsProvider('')),profile=ref.watch(userProfileProvider);
    return RefreshIndicator(onRefresh:()async{ref.invalidate(dashboardProvider);ref.invalidate(baseCurrencyProvider);ref.invalidate(transactionsProvider(null));ref.invalidate(accountsProvider(''));},child:ListView(padding:const EdgeInsets.fromLTRB(16,10,16,90),children:[
      Row(children:[profile.when(data:(p)=>AccountAvatar(name:p['user_name']??'سمير الحسامي'),loading:()=>const AccountAvatar(name:'س'),error:(_,__)=>const AccountAvatar(name:'س')),const SizedBox(width:10),Expanded(child:profile.when(data:(p)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p['user_name']?.isNotEmpty==true?p['user_name']!:'سمير الحسامي',style:const TextStyle(fontWeight:FontWeight.w800,fontSize:17)),Text(p['address_ar']?.isNotEmpty==true?p['address_ar']!:'دفتر الحسابات',style:const TextStyle(fontSize:12))]),loading:()=>const Text('سمير الحسامي'),error:(_,__)=>const Text('سمير الحسامي'))),IconButton(onPressed:()=>context.push('/search'),icon:const Icon(Icons.search_rounded))]),
      const SizedBox(height:12),TextField(readOnly:true,onTap:()=>context.push('/search'),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'ابحث عن عميل أو عملية...')),const SizedBox(height:12),_newAccountCard(context,ref),const SizedBox(height:12),
      totals.when(loading:()=>const LinearProgressIndicator(),error:(e,s)=>Text('$e'),data:(v){final code=currency.asData?.value??'YER',net=(v['credit']??0)-(v['debit']??0);return Card(color:Theme.of(context).colorScheme.primary,child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[const Text('الرصيد الصافي',style:TextStyle(color:Colors.white70)),const SizedBox(height:4),Text(money(net.abs(),code),style:const TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),Text(net>0?'الصافي له':net<0?'الصافي عليه':'متوازن',style:const TextStyle(color:Colors.white70,fontWeight:FontWeight.w800)),const SizedBox(height:16),Row(children:[_BalanceMini(title:'إجمالي لي',value:(v['credit']??0).toDouble(),currency:code),const SizedBox(width:10),_BalanceMini(title:'إجمالي علي',value:(v['debit']??0).toDouble(),currency:code)])])));}),
      const SizedBox(height:18),const SectionTitle(title:'الحسابات المهمة'),const SizedBox(height:8),accounts.when(loading:()=>const _SkeletonList(),error:(e,s)=>Text('$e'),data:(items)=>items.isEmpty?const EmptyState(title:'لا توجد حسابات',subtitle:'استخدم زر الإضافة في الأسفل لإضافة عميل أو مورد.'):Column(children:items.take(4).map((a)=>_accountTile(context,a)).toList())),
      const SizedBox(height:18),const SectionTitle(title:'آخر العمليات',action:'عرض الكل'),const SizedBox(height:8),transactions.when(loading:()=>const _SkeletonList(),error:(e,s)=>Text('$e'),data:(items)=>items.isEmpty?const EmptyState(title:'لا توجد عمليات',subtitle:'أضف أول عملية لتظهر هنا.'):Column(children:items.take(5).map((t)=>_transactionTile(context,ref,t)).toList()))
    ]));
  }
  Widget _newAccountCard(BuildContext context,WidgetRef ref)=>Card(child:Padding(padding:const EdgeInsets.fromLTRB(16,14,16,14),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('إضافة حساب جديد',textAlign:TextAlign.right,style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>showAddAccountSheet(context,ref,initialType:'supplier'),icon:const Icon(Icons.business_outlined),label:const Text('مورد'))),const SizedBox(width:12),Expanded(child:OutlinedButton.icon(onPressed:()=>showAddAccountSheet(context,ref,initialType:'customer'),icon:const Icon(Icons.person_add_alt_1),label:const Text('عميل')))])])));
  Widget _accountTile(BuildContext context,Account account)=>Card(margin:const EdgeInsets.only(bottom:8),child:ListTile(onTap:()=>context.push('/accounts/${account.id}'),leading:AccountAvatar(name:account.name),title:Text(account.name,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(account.phone.isEmpty?'حساب':account.phone),trailing:const Icon(Icons.chevron_left)));
  Widget _transactionTile(BuildContext context,WidgetRef ref,TransactionItem item)=>Card(margin:const EdgeInsets.only(bottom:8),child:ListTile(onTap:()=>_transactionActions(context,ref,item),leading:AccountAvatar(name:'عملية',radius:21),title:const Text('عملية',style:TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${dateAr(item.date)} • ${item.note.isEmpty?item.category:item.note}'),trailing:MoneyAmount(value:item.amount,currency:item.currency,positive:item.type=='credit')));
  Future<void> _transactionActions(BuildContext context,WidgetRef ref,TransactionItem item)async{await showModalBottomSheet<void>(context:context,showDragHandle:true,builder:(sheetContext)=>SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(16,4,16,18),child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(leading:Icon(item.type=='credit'?Icons.arrow_downward:Icons.arrow_upward),title:const Text('عملية',style:TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${item.amount.toStringAsFixed(2)} ${item.currency} • ${dateAr(item.date)}')),const Divider(),ListTile(leading:const Icon(Icons.edit_outlined),title:const Text('تعديل العملية'),onTap:(){Navigator.pop(sheetContext);context.push('/edit-transaction/${item.id}');}),ListTile(leading:const Icon(Icons.delete_outline,color:Colors.red),title:const Text('حذف العملية',style:TextStyle(color:Colors.red,fontWeight:FontWeight.w700)),onTap:()async{Navigator.pop(sheetContext);final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('حذف العملية'),content:const Text('هل تريد حذف هذه العملية نهائيًا؟ سيتم تحديث الرصيد والإجماليات.'),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('إلغاء')),FilledButton.tonal(onPressed:()=>Navigator.pop(ctx,true),child:const Text('حذف'))]))??false;if(!ok)return;try{await ref.read(repositoryProvider).deleteTransaction(item.id);ref.invalidate(transactionsProvider(null));ref.invalidate(transactionsProvider(item.accountId));ref.invalidate(accountProvider(item.accountId));ref.invalidate(accountsProvider(''));ref.invalidate(dashboardProvider);if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم حذف العملية ✓')));}catch(e){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر حذف العملية: $e')));}})]))));}
}
class _BalanceMini extends StatelessWidget{final String title;final double value;final String currency;const _BalanceMini({required this.title,required this.value,required this.currency});@override Widget build(BuildContext context)=>Expanded(child:Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white.withOpacity(.12),borderRadius:BorderRadius.circular(12)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:Colors.white70,fontSize:12)),const SizedBox(height:4),Text(money(value,currency),style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w800))])));}
class _SkeletonList extends StatelessWidget{const _SkeletonList();@override Widget build(BuildContext context)=>Column(children:List.generate(3,(i)=>const Card(child:SizedBox(height:68))));}
