import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../core/providers.dart';
import '../../domain/models.dart';
import '../../core/utils/formatters.dart';
import '../../shared/widgets.dart';
class TransactionsPage extends ConsumerStatefulWidget{const TransactionsPage({super.key});@override ConsumerState<TransactionsPage> createState()=>_TransactionsPageState();}
class _TransactionsPageState extends ConsumerState<TransactionsPage>{final search=TextEditingController();@override void dispose(){search.dispose();super.dispose();}
Future<void> _delete(TransactionItem item)async{final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('حذف العملية'),content:const Text('هل تريد حذف هذه العملية نهائيًا؟ سيتم تحديث رصيد الحساب والإجماليات بعد الحذف.'),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('إلغاء')),FilledButton.tonal(onPressed:()=>Navigator.pop(ctx,true),child:const Text('حذف'))]))??false;if(!ok)return;try{await ref.read(repositoryProvider).deleteTransaction(item.id);ref.invalidate(transactionsProvider(null));ref.invalidate(transactionsProvider(item.accountId));ref.invalidate(accountProvider(item.accountId));ref.invalidate(accountsProvider(''));ref.invalidate(dashboardProvider);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم حذف العملية ✓')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر حذف العملية: $e')));}}
Future<void> _actions(TransactionItem item)async{await showModalBottomSheet<void>(context:context,showDragHandle:true,builder:(sheetContext)=>SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(16,4,16,18),child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(leading:const Icon(Icons.receipt_long_outlined),title:const Text('العملية'),subtitle:Text('${item.amount.toStringAsFixed(2)} ${item.currency} • ${dateAr(item.date)}')),const Divider(),ListTile(leading:const Icon(Icons.edit_outlined),title:const Text('تعديل العملية'),onTap:(){Navigator.pop(sheetContext);context.push('/edit-transaction/${item.id}');}),ListTile(leading:const Icon(Icons.delete_outline,color:Colors.red),title:const Text('حذف العملية',style:TextStyle(color:Colors.red,fontWeight:FontWeight.w700)),onTap:(){Navigator.pop(sheetContext);_delete(item);})]))));}
@override Widget build(BuildContext context){final transactions=ref.watch(transactionsProvider(null));return Column(children:[const AppHeader(title:'العمليات',back:false),Padding(padding:const EdgeInsets.fromLTRB(16,8,16,10),child:TextField(controller:search,onChanged:(_)=>setState((){}),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'ابحث عن مبلغ أو وصف أو عملة...'))),Expanded(child:transactions.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,s)=>Center(child:Text('$e')),data:(all){final q=search.text.trim().toLowerCase();final list=q.isEmpty?all:all.where((item)=>('${item.amount} ${item.currency} ${item.category} ${item.note}').toLowerCase().contains(q)).toList();if(list.isEmpty)return const EmptyState(title:'لا توجد عمليات',subtitle:'ابدأ بإضافة عملية مالية.');return ListView.separated(padding:const EdgeInsets.fromLTRB(16,8,16,90),itemCount:list.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(context,i){final item=list[i],positive=item.type=='credit';return Card(child:ListTile(onTap:()=>_actions(item),leading:CircleAvatar(backgroundColor:(positive?Colors.green:Colors.red).withOpacity(.12),child:Icon(positive?Icons.arrow_downward:Icons.arrow_upward,color:positive?Colors.green:Colors.red)),title:const Text('عملية',style:TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${dateAr(item.date)} • ${item.note.isEmpty?item.category:item.note}'),trailing:MoneyAmount(value:item.amount,currency:item.currency,positive:positive)));}})}))]);}}
