import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../core/constants/app_constants.dart';
import '../core/utils/formatters.dart';
class AppHeader extends StatelessWidget implements PreferredSizeWidget{
  final String title;final List<Widget>? actions;final bool back;
  const AppHeader({super.key,required this.title,this.actions,this.back=true});
  @override Size get preferredSize=>const Size.fromHeight(kToolbarHeight);
  @override Widget build(BuildContext context)=>AppBar(title:Text(title,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:18)),leading:back?IconButton(onPressed:(){if(Navigator.of(context).canPop()){Navigator.of(context).pop();}else{GoRouter.of(context).go('/home');}},icon:const Icon(Icons.arrow_back_ios_new_rounded,size:19)):null,actions:actions);
}
class SectionTitle extends StatelessWidget{final String title;final String? action;final VoidCallback? onTap;const SectionTitle({super.key,required this.title,this.action,this.onTap});@override Widget build(BuildContext context)=>Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(title,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800)),if(action!=null)TextButton(onPressed:onTap,child:Text(action!))]);}
class MoneyAmount extends StatelessWidget{final num value;final String currency;final bool positive;const MoneyAmount({super.key,required this.value,required this.currency,this.positive=true});@override Widget build(BuildContext context)=>Text((positive?'+':'')+money(value,currency),style:TextStyle(fontWeight:FontWeight.w900,color:positive?const Color(AppConstants.primary):Colors.redAccent,fontSize:16));}
class AccountAvatar extends StatelessWidget{final String name;final double radius;const AccountAvatar({super.key,required this.name,this.radius=22});@override Widget build(BuildContext context)=>CircleAvatar(radius:radius,backgroundColor:Theme.of(context).colorScheme.primaryContainer,child:Text(name.isEmpty?'؟':name.characters.first,style:TextStyle(color:Theme.of(context).colorScheme.primary,fontWeight:FontWeight.bold)));}
class EmptyState extends StatelessWidget{final String title;final String subtitle;final IconData icon;final VoidCallback? onPressed;const EmptyState({super.key,required this.title,required this.subtitle,this.icon=Icons.receipt_long_rounded,this.onPressed});@override Widget build(BuildContext context)=>Center(child:Padding(padding:const EdgeInsets.all(32),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:60,color:Theme.of(context).colorScheme.primary),const SizedBox(height:14),Text(title,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:6),Text(subtitle,textAlign:TextAlign.center),if(onPressed!=null)...[const SizedBox(height:16),FilledButton.icon(onPressed:onPressed,icon:const Icon(Icons.add),label:const Text('إضافة'))]])));}
class PrimaryButton extends StatelessWidget{final String label;final VoidCallback? onPressed;final IconData? icon;const PrimaryButton({super.key,required this.label,this.onPressed,this.icon});@override Widget build(BuildContext context)=>SizedBox(width:double.infinity,height:52,child:FilledButton.icon(onPressed:onPressed,icon:Icon(icon??Icons.check_rounded),label:Text(label,style:const TextStyle(fontWeight:FontWeight.bold))));}
class StatCard extends StatelessWidget{final String label;final String value;final IconData icon;const StatCard({super.key,required this.label,required this.value,required this.icon});@override Widget build(BuildContext context)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:Theme.of(context).colorScheme.primary),const SizedBox(height:8),Text(label,style:Theme.of(context).textTheme.bodySmall),const SizedBox(height:3),Text(value,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:17))])));}