import 'dart:convert';
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/providers.dart';

class BackupPage extends ConsumerStatefulWidget{const BackupPage({super.key});@override ConsumerState<BackupPage> createState()=>_BackupPageState();}
class _BackupPageState extends ConsumerState<BackupPage>{bool busy=false;String account='';
@override void initState(){super.initState();_load();}
Future<void> _load()async{account=await ref.read(repositoryProvider).getSetting('backup_account')??'';if(mounted)setState((){});}
Future<void> _saveLocal()async{if(busy)return;setState(()=>busy=true);try{final data=await ref.read(repositoryProvider).exportData();final json=const JsonEncoder.withIndent('  ').convert(data);final path=await FilePicker.platform.saveFile(dialogTitle:'حفظ النسخة الاحتياطية',fileName:'dftar_backup.json',type:FileType.custom,allowedExtensions:const['json'],bytes:utf8.encode(json));if(path!=null&&mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم حفظ النسخة الاحتياطية ✓')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر الحفظ: $e')));}finally{if(mounted)setState(()=>busy=false);}}
Future<void> _restore()async{final r=await FilePicker.platform.pickFiles(type:FileType.custom,allowedExtensions:const['json'],withData:true);if(r==null)return;try{final f=r.files.single;final bytes=f.bytes??await File(f.path!).readAsBytes();final data=jsonDecode(utf8.decode(bytes));if(data is! Map<String,dynamic>)throw const FormatException('ملف غير صالح');await ref.read(repositoryProvider).importData(data,merge:false);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تمت الاستعادة ✓')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('فشلت الاستعادة: $e')));}}
Future<void> _connect()async{try{final email=await ref.read(backupCoordinatorProvider).connectAndBackup();if(mounted){setState(()=>account=email);ScaffoldMessenger.of(context).showSnackBar(Text('تم الحفظ للحساب: $email') as SnackBar);}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر الربط: $e')));}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('النسخ الاحتياطي')),body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(leading:const Icon(Icons.cloud_outlined),title:const Text('Google Drive'),subtitle:Text(account.isEmpty?'غير مرتبط':account),trailing:FilledButton(onPressed:_connect,child:const Text('ربط')))),const SizedBox(height:12),Card(child:Column(children:[ListTile(onTap:busy?null:_saveLocal,leading:const Icon(Icons.save_alt),title:const Text('حفظ نسخة محلية'),trailing:const Icon(Icons.chevron_left)),const Divider(height:1),ListTile(onTap:_restore,leading:const Icon(Icons.restore),title:const Text('استعادة من الهاتف'),trailing:const Icon(Icons.chevron_left)),const Divider(height:1),ListTile(onTap:()=>ref.read(backupCoordinatorProvider).backupNow(),leading:const Icon(Icons.backup),title:const Text('نسخ الآن إلى Google Drive'),trailing:const Icon(Icons.chevron_left))]))]));}
