import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/providers.dart';
import '../../shared/widgets.dart';
class OtherSettingsPage extends ConsumerStatefulWidget {const OtherSettingsPage({super.key});@override ConsumerState<OtherSettingsPage> createState()=>_OtherSettingsPageState();}
class _OtherSettingsPageState extends ConsumerState<OtherSettingsPage>{bool reminders=true,amountWords=false,dark=false;String sort='updated_desc';
@override void initState(){super.initState();_load();}
Future<void> _load()async{final r=ref.read(repositoryProvider);reminders=(await r.getSetting('reminders_enabled')??'1')=='1';amountWords=(await r.getSetting('amount_words')??'0')=='1';sort=await r.getSetting('accounts_sort')??'updated_desc';dark=ref.read(themeModeProvider)==ThemeMode.dark;if(mounted)setState((){});}
Future<void> _set(String k,String v)=>ref.read(repositoryProvider).setSetting(k,v);
@override Widget build(BuildContext context)=>Scaffold(appBar:const AppHeader(title:'خيارات أخرى'),body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:Column(children:[SwitchListTile(value:reminders,onChanged:(v){setState(()=>reminders=v);_set('reminders_enabled',v?'1':'0');},title:const Text('التذكيرات والتنبيهات')),const Divider(height:1),SwitchListTile(value:amountWords,onChanged:(v){setState(()=>amountWords=v);_set('amount_words',v?'1':'0');},title:const Text('إظهار المبلغ كتابةً')),const Divider(height:1),SwitchListTile(value:dark,onChanged:(v){setState(()=>dark=v);ref.read(themeModeProvider.notifier).state=v?ThemeMode.dark:ThemeMode.light;_set('theme_mode',v?'dark':'light');},title:const Text('الوضع الليلي'))])),const SizedBox(height:14),Card(child:Padding(padding:const EdgeInsets.all(16),child:DropdownButtonFormField<String>(initialValue:sort,items:const[DropdownMenuItem(value:'name_asc',child:Text('الاسم: من أ إلى ي')),DropdownMenuItem(value:'name_desc',child:Text('الاسم: من ي إلى أ')),DropdownMenuItem(value:'balance_desc',child:Text('الأكثر رصيدًا')),DropdownMenuItem(value:'balance_asc',child:Text('الأقل رصيدًا')),DropdownMenuItem(value:'updated_desc',child:Text('الأحدث أولًا'))],onChanged:(v){if(v!=null){setState(()=>sort=v);_set('accounts_sort',v);}},decoration:const InputDecoration(labelText:'فرز الحسابات'))))]));}