import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import '../../core/providers.dart';
import '../../shared/widgets.dart';

class ProfileSettingsPage extends ConsumerStatefulWidget { const ProfileSettingsPage({super.key}); @override ConsumerState<ProfileSettingsPage> createState()=>_ProfileSettingsPageState(); }
class _ProfileSettingsPageState extends ConsumerState<ProfileSettingsPage>{
 final name=TextEditingController(),nameEn=TextEditingController(),role=TextEditingController(),phone=TextEditingController(),address=TextEditingController(),addressEn=TextEditingController(); String logo=''; bool loading=true,saving=false;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{final p=await ref.read(repositoryProvider).userProfile();name.text=p['user_name']??'';nameEn.text=p['user_name_en']??'';phone.text=p['phone']??'';address.text=p['address_ar']??'';addressEn.text=p['address_en']??'';logo=p['logo_path']??'';role.text=await ref.read(repositoryProvider).getSetting('user_role')??'';if(mounted)setState(()=>loading=false);}
 @override void dispose(){for(final c in [name,nameEn,role,phone,address,addressEn])c.dispose();super.dispose();}
 Future<void> _save()async{if(name.text.trim().isEmpty)return;setState(()=>saving=true);final repo=ref.read(repositoryProvider);await repo.setSetting('user_name',name.text.trim());await repo.setSetting('user_name_en',nameEn.text.trim());await repo.setSetting('user_role',role.text.trim());await repo.setSetting('phone',phone.text.trim());await repo.setSetting('address_ar',address.text.trim());await repo.setSetting('address_en',addressEn.text.trim());await repo.setSetting('logo_path',logo);ref.invalidate(userProfileProvider);if(mounted){setState(()=>saving=false);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم حفظ بيانات المستخدم ✓')));}}
 @override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));final hasCustomLogo=logo.isNotEmpty&&File(logo).existsSync();return Scaffold(appBar:const AppHeader(title:'تعديل بيانات المستخدم'),body:ListView(padding:const EdgeInsets.fromLTRB(16,10,16,30),children:[Center(child:CircleAvatar(radius:52,backgroundImage:hasCustomLogo?FileImage(File(logo)):const AssetImage('assets/app_logo.jpg') as ImageProvider)),const SizedBox(height:8),Center(child:TextButton.icon(onPressed:()async{final x=await ImagePicker().pickImage(source:ImageSource.gallery);if(x!=null)setState(()=>logo=x.path);},icon:const Icon(Icons.image_outlined),label:const Text('اختيار الشعار'))),const SizedBox(height:12),const SectionTitle(title:'البيانات العربية'),TextField(controller:name,decoration:const InputDecoration(labelText:'الاسم *',prefixIcon:Icon(Icons.person_outline))),const SizedBox(height:10),TextField(controller:role,decoration:const InputDecoration(labelText:'الصفة / المسمى الوظيفي',prefixIcon:Icon(Icons.badge_outlined))),const SizedBox(height:10),TextField(controller:address,decoration:const InputDecoration(labelText:'العنوان',prefixIcon:Icon(Icons.location_on_outlined))),const SizedBox(height:10),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'رقم الهاتف',prefixIcon:Icon(Icons.phone_outlined))),const SizedBox(height:18),const SectionTitle(title:'English'),TextField(controller:nameEn,decoration:const InputDecoration(labelText:'Name')),const SizedBox(height:10),TextField(controller:addressEn,decoration:const InputDecoration(labelText:'Address')),const SizedBox(height:20),PrimaryButton(label:saving?'جاري الحفظ...':'حفظ البيانات',icon:Icons.save,onPressed:saving?null:_save)]));}
}