import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:file_picker/file_picker.dart';
import 'package:go_router/go_router.dart';
import '../../core/providers.dart';
import '../../shared/widgets.dart';

class SettingsPage extends ConsumerStatefulWidget{const SettingsPage({super.key});@override ConsumerState<SettingsPage> createState()=>_SettingsPageState();}
class _SettingsPageState extends ConsumerState<SettingsPage>{bool pinSet=false,autoBackup=false,notifySuccess=true,notifyFailure=true;String backupAccount='',localPath='';
@override void initState(){super.initState();_load();}
Future<void> _load()async{final r=ref.read(repositoryProvider);pinSet=await ref.read(securityProvider).hasPin();autoBackup=(await r.getSetting('backup_auto')??'0')=='1';backupAccount=await r.getSetting('backup_account')??'';localPath=await r.getSetting('backup_local_path')??'';notifySuccess=(await r.getSetting('backup_notify_success')??'1')=='1';notifyFailure=(await r.getSetting('backup_notify_failure')??'1')=='1';if(mounted)setState((){});}
Future<void> _deleteAllData()async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('حذف جميع البيانات؟'),content:const Text('سيتم حذف العملاء والموردين والعمليات والمرفقات وسجل النشاط نهائيًا. إعدادات التطبيق ستبقى.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('إلغاء')),FilledButton(style:FilledButton.styleFrom(backgroundColor:Colors.red),onPressed:()=>Navigator.pop(c,true),child:const Text('حذف نهائي'))]))??false;if(!ok)return;await ref.read(repositoryProvider).deleteAllLedgerData();ref.invalidate(accountsProvider(''));ref.invalidate(transactionsProvider(null));ref.invalidate(dashboardProvider);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم حذف جميع بيانات الدفتر بنجاح')));}
Future<void> _toggleBackup(bool value)async{setState(()=>autoBackup=value);await ref.read(repositoryProvider).setSetting('backup_auto',value?'1':'0');if(value)await ref.read(backupCoordinatorProvider).checkAndBackup();}
Future<void> _chooseFolder()async{final path=await FilePicker.platform.getDirectoryPath();if(path!=null){await ref.read(repositoryProvider).setSetting('backup_local_path',path);if(mounted)setState(()=>localPath=path);}}
Future<void> _chooseTime()async{final raw=await ref.read(repositoryProvider).getSetting('backup_time')??'02:00';final parts=raw.split(':');final initial=TimeOfDay(hour:int.tryParse(parts.first)??2,minute:int.tryParse(parts.length>1?parts[1]:'0')??0);final time=await showTimePicker(context:context,initialTime:initial);if(time!=null){final value='${time.hour.toString().padLeft(2,'0')}:${time.minute.toString().padLeft(2,'0')}';await ref.read(repositoryProvider).setSetting('backup_time',value);if(mounted)setState((){});}}
@override Widget build(BuildContext context)=>Scaffold(appBar:const AppHeader(title:'الإعدادات'),body:ListView(padding:const EdgeInsets.fromLTRB(16,10,16,30),children:[
const SectionTitle(title:'الحساب والتطبيق'),Card(child:Column(children:[_item('بيانات المستخدم','الاسم والشعار والصفة والعنوان والرقم',Icons.person_outline,'/settings/profile'),const Divider(height:1),_item('خيارات الطباعة','إعدادات الشعار والملخص واتجاه الطباعة',Icons.print_outlined,'/settings/printer'),const Divider(height:1),_item('خيارات الأمان',pinSet?'PIN من 6 أرقام مفعل':'إضافة كلمة مرور PIN والبصمة',Icons.security_outlined,'/settings/security')])),
const SizedBox(height:16),const SectionTitle(title:'النسخ الاحتياطي'),Card(child:Column(children:[ListTile(onTap:()=>context.push('/backup'),leading:const Icon(Icons.cloud_outlined),title:const Text('Google Drive'),subtitle:Text(backupAccount.isEmpty?'ربط الحساب ورفع النسخة':'مرتبط: '+backupAccount),trailing:const Icon(Icons.chevron_left)),const Divider(height:1),SwitchListTile(value:autoBackup,onChanged:_toggleBackup,title:const Text('النسخ الاحتياطي التلقائي'),subtitle:const Text('تحديث عند الاتصال ومرة يوميًا حسب الوقت المحدد')),const Divider(height:1),ListTile(onTap:()=>context.push('/backup'),leading:const Icon(Icons.settings_backup_restore_outlined),title:const Text('حفظ / استيراد نسخة احتياطية'),trailing:const Icon(Icons.chevron_left)),const Divider(height:1),ListTile(onTap:_chooseFolder,leading:const Icon(Icons.folder_outlined),title:const Text('تحديد مجلد الحفظ المحلي'),subtitle:Text(localPath.isEmpty?'لم يتم تحديد مجلد':localPath),trailing:const Icon(Icons.chevron_left)),const Divider(height:1),ListTile(onTap:_chooseTime,leading:const Icon(Icons.schedule),title:const Text('وقت النسخ الاحتياطي'),subtitle:FutureBuilder<String?>(future:ref.read(repositoryProvider).getSetting('backup_time'),builder:(c,s)=>Text(s.data??'02:00')),trailing:const Icon(Icons.chevron_left)),const Divider(height:1),SwitchListTile(value:notifySuccess,onChanged:(v){setState(()=>notifySuccess=v);ref.read(repositoryProvider).setSetting('backup_notify_success',v?'1':'0');},title:const Text('إشعار عند نجاح النسخ')),SwitchListTile(value:notifyFailure,onChanged:(v){setState(()=>notifyFailure=v);ref.read(repositoryProvider).setSetting('backup_notify_failure',v?'1':'0');},title:const Text('إشعار عند فشل النسخ'))])),
const SizedBox(height:16),const SectionTitle(title:'الإشعارات والرسائل'),Card(child:_item('الإشعارات والرسائل','نص كشف الحساب وواتساب والتاريخ',Icons.notifications_outlined,'/settings/notifications')),
const SizedBox(height:16),const SectionTitle(title:'خيارات أخرى'),Card(child:_item('خيارات أخرى','التذكيرات والمبلغ كتابةً والفرز والوضع الليلي',Icons.tune,'/settings/other')),
const SizedBox(height:16),Card(child:ListTile(onTap:()=>context.push('/currencies'),leading:const Icon(Icons.currency_exchange),title:const Text('العملات وأسعار الصرف'),trailing:const Icon(Icons.chevron_left))),
const SizedBox(height:10),Card(child:ListTile(onTap:_deleteAllData,leading:const Icon(Icons.delete_sweep_outlined,color:Colors.red),title:const Text('حذف جميع البيانات',style:TextStyle(color:Colors.red,fontWeight:FontWeight.w800)),trailing:const Icon(Icons.chevron_left))) ]));
Widget _item(String title,String subtitle,IconData icon,String route)=>ListTile(onTap:()=>context.push(route),leading:Icon(icon,color:Theme.of(context).colorScheme.primary),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(subtitle),trailing:const Icon(Icons.chevron_left));}
